module_version: 1.0
var:
  - name: paths
    default:
{% if 'ansible' in item.1 %}
      - /var/log/ansible.log
{% elif 'aptitude' in item.1 %}
      - /var/log/aptitude
{% elif 'mail' in item.1 %}
      - /var/log/mail.log
{% elif 'dpkg' in item.1 %}
      - /var/log/dpkg.log
{% endif %}

  - name: convert_timezone
    default: false
    # if ES < 6.1.0, this flag switches to false automatically when evaluating the
    # pipeline
    min_elasticsearch_version:
      version: 6.1.0
      value: false

ingest_pipeline: ingest/pipeline.json
input: config/log.yml
