module_version: 1.0
var:
  - name: paths
    default:
{% if 'nagios' in item.1 %}
      - /var/log/nagios*/nagios.log
{% elif 'pentaho' in item.1 %}
      -  /home/etl/logs/*/*.log
{% elif 'mongos' in item.1 %}
      -  /var/log/mongodb/mongos.log
{% elif 'squid' in item.1 %}
      -  /var/log/*squid*/*.log
{% elif 'proftpd' in item.1 %}
      -  /var/log/proftpd/*.log
      -  /root/cron/scripts/enterprise_datafeed/sendlog.log
      -  /var/log/xferlog
{% elif 'smarty-artie' in item.1 %}
      -  /reputation/var/log/smarty-artie/*.log
{% endif %}

  - name: convert_timezone
    default: false
    # if ES < 6.1.0, this flag switches to false automatically when evaluating the
    # pipeline
    min_elasticsearch_version:
      version: 6.1.0
      value: false

ingest_pipeline: ingest/pipeline.json
input: config/log.yml
